// Auth action types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';

// Worker action types
export const FETCH_WORKERS_REQUEST = 'FETCH_WORKERS_REQUEST';
export const FETCH_WORKERS_SUCCESS = 'FETCH_WORKERS_SUCCESS';
export const FETCH_WORKERS_FAILURE = 'FETCH_WORKERS_FAILURE';

// Farmer action types
export const FETCH_FARMERS_REQUEST = 'FETCH_FARMERS_REQUEST';
export const FETCH_FARMERS_SUCCESS = 'FETCH_FARMERS_SUCCESS';
export const FETCH_FARMERS_FAILURE = 'FETCH_FARMERS_FAILURE';

// Job action types
export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

// Payment action types
export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE';

// Rating action types
export const CREATE_RATING_REQUEST = 'CREATE_RATING_REQUEST';
export const CREATE_RATING_SUCCESS = 'CREATE_RATING_SUCCESS';
export const CREATE_RATING_FAILURE = 'CREATE_RATING_FAILURE';

export const FETCH_FARMER_RATINGS_REQUEST = 'FETCH_FARMER_RATINGS_REQUEST';
export const FETCH_FARMER_RATINGS_SUCCESS = 'FETCH_FARMER_RATINGS_SUCCESS';
export const FETCH_FARMER_RATINGS_FAILURE = 'FETCH_FARMER_RATINGS_FAILURE';

export const FETCH_WORKER_RATINGS_REQUEST = 'FETCH_WORKER_RATINGS_REQUEST';
export const FETCH_WORKER_RATINGS_SUCCESS = 'FETCH_WORKER_RATINGS_SUCCESS';
export const FETCH_WORKER_RATINGS_FAILURE = 'FETCH_WORKER_RATINGS_FAILURE';

export const FETCH_FARMER_AVERAGE_RATING_REQUEST = 'FETCH_FARMER_AVERAGE_RATING_REQUEST';
export const FETCH_FARMER_AVERAGE_RATING_SUCCESS = 'FETCH_FARMER_AVERAGE_RATING_SUCCESS';
export const FETCH_FARMER_AVERAGE_RATING_FAILURE = 'FETCH_FARMER_AVERAGE_RATING_FAILURE';

export const FETCH_WORKER_AVERAGE_RATING_REQUEST = 'FETCH_WORKER_AVERAGE_RATING_REQUEST';
export const FETCH_WORKER_AVERAGE_RATING_SUCCESS = 'FETCH_WORKER_AVERAGE_RATING_SUCCESS';
export const FETCH_WORKER_AVERAGE_RATING_FAILURE = 'FETCH_WORKER_AVERAGE_RATING_FAILURE';

// Review action types
export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';